eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@discovery-server:8761/eureka

server:
  port: 0
spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: broker:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.programming.notificationservice.OrderPlacedEvent
      group-id: notificationId
    template:
      default-topic: notificationTopic
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0