app:
  eureka-server: discovery-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@discovery-server:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          predicates:
            - Path=/api/product
          uri: lb://product-service
        - id: order-service
          predicates:
            - Path=/api/order
          uri: lb://order-service
        - filters:
            - SetPath=/
          id: discovery-server
          predicates:
            - Path=/eureka/web
          uri: http://root:123456@discovery-server:8761/eureka
        - id: discovery-server-static
          predicates:
            - Path=/eureka/**
          uri: http://root:123456@discovery-server:8761/eureka
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8181/realms/spring-boot-microservices-realm
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

