eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
server:
  port: 8761
  eureka:
    client:
      serviceUrl:
        defaultZone: http://user:password@discovery-server:8761/eureka

spring:
  security:
    user:
      name: root
      password: 123456
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0