eureka:
  client:
    serviceUrl:
      defaultZone:  http://root:123456@discovery-server:8761/eureka
server:
  port: 0
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/product-service
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0